# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cgruska/development/groggScript

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cgruska/development/groggScript

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cgruska/development/groggScript/CMakeFiles /Users/cgruska/development/groggScript//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cgruska/development/groggScript/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GroggScript

# Build rule for target.
GroggScript: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GroggScript
.PHONY : GroggScript

# fast build rule for target.
GroggScript/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GroggScript.dir/build.make CMakeFiles/GroggScript.dir/build
.PHONY : GroggScript/fast

src/lexer/tokenizer.o: src/lexer/tokenizer.cpp.o
.PHONY : src/lexer/tokenizer.o

# target to build an object file
src/lexer/tokenizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GroggScript.dir/build.make CMakeFiles/GroggScript.dir/src/lexer/tokenizer.cpp.o
.PHONY : src/lexer/tokenizer.cpp.o

src/lexer/tokenizer.i: src/lexer/tokenizer.cpp.i
.PHONY : src/lexer/tokenizer.i

# target to preprocess a source file
src/lexer/tokenizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GroggScript.dir/build.make CMakeFiles/GroggScript.dir/src/lexer/tokenizer.cpp.i
.PHONY : src/lexer/tokenizer.cpp.i

src/lexer/tokenizer.s: src/lexer/tokenizer.cpp.s
.PHONY : src/lexer/tokenizer.s

# target to generate assembly for a file
src/lexer/tokenizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GroggScript.dir/build.make CMakeFiles/GroggScript.dir/src/lexer/tokenizer.cpp.s
.PHONY : src/lexer/tokenizer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GroggScript.dir/build.make CMakeFiles/GroggScript.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GroggScript.dir/build.make CMakeFiles/GroggScript.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GroggScript.dir/build.make CMakeFiles/GroggScript.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/syntax_tree/syntax_tree.o: src/syntax_tree/syntax_tree.cpp.o
.PHONY : src/syntax_tree/syntax_tree.o

# target to build an object file
src/syntax_tree/syntax_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GroggScript.dir/build.make CMakeFiles/GroggScript.dir/src/syntax_tree/syntax_tree.cpp.o
.PHONY : src/syntax_tree/syntax_tree.cpp.o

src/syntax_tree/syntax_tree.i: src/syntax_tree/syntax_tree.cpp.i
.PHONY : src/syntax_tree/syntax_tree.i

# target to preprocess a source file
src/syntax_tree/syntax_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GroggScript.dir/build.make CMakeFiles/GroggScript.dir/src/syntax_tree/syntax_tree.cpp.i
.PHONY : src/syntax_tree/syntax_tree.cpp.i

src/syntax_tree/syntax_tree.s: src/syntax_tree/syntax_tree.cpp.s
.PHONY : src/syntax_tree/syntax_tree.s

# target to generate assembly for a file
src/syntax_tree/syntax_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GroggScript.dir/build.make CMakeFiles/GroggScript.dir/src/syntax_tree/syntax_tree.cpp.s
.PHONY : src/syntax_tree/syntax_tree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GroggScript"
	@echo "... src/lexer/tokenizer.o"
	@echo "... src/lexer/tokenizer.i"
	@echo "... src/lexer/tokenizer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/syntax_tree/syntax_tree.o"
	@echo "... src/syntax_tree/syntax_tree.i"
	@echo "... src/syntax_tree/syntax_tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

