#ifndef GROGG_SCRIPT_OPERATORS_HPP
#define GROGG_SCRIPT_OPERATORS_HPP
#define MULTIPLY_OPERATOR '*'
#define DIVIDE_OPERATOR '/'
#define PLUS_OPERATOR '+'
#define MINUS_OPERATOR '-'
#define GREATER_THAN_OPERATOR '>'
#define LESS_THAN_OPERATOR '<'
#define EQUALS_OPERATOR "=="
#define ASSIGNMENT_OPERATOR '='
#endif